version: "3.4"

volumes:
  redis:
  # The contents of /root, so that bash and ipython can store history
  web_home:

services:
  solidauth:
    build: ./
    environment:
      - VIRTUAL_HOST=clara-auth.finishthings.com
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST=clara-auth.finishthings.com
      - LETSENCRYPT_EMAIL=alastair@porter.net.nz
      - CONFIG_REDIS_URL=redis://redis:6379/0
      - CONFIG_SECRET_KEY=12341323123123123
      - CONFIG_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:example@db/solid_oidc
      - CONFIG_REDIRECT_URL=https://clara-auth.finishthings.com/redirect
      - CONFIG_BASE_URL=https://clara-auth.finishthings.com
      - CONFIG_BACKEND=db
    command: uwsgi --die-on-term uwsgi.ini
    expose:
      - "8000"
    networks:
      - clara

networks:
  clara:
    name: trompa-align_default
    external: true
